[package]
name = "kivi-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
kivi-types.workspace = true
bytes.workspace = true
thiserror.workspace = true
lz4_flex.workspace = true
crc32c.workspace = true
compio.workspace = true
async-channel.workspace = true

[dev-dependencies]
tempfile.workspace = true
proptest.workspace = true
divan.workspace = true

[lints]
workspace = true

[[bench]]
name = "fabric"
harness = false
