//! Deterministic simulation RNG with a project-owned, frozen algorithm.
//!
//! [`SimRng`] implements a SplitMix64-style generator (a single `u64` of
//! state, one addition and three xor-shift/multiply mixes per draw) with its
//! constants pinned in this file. Replay stability therefore depends only on
//! this source text — never on a dependency version, platform `rand`
//! implementation, or hardware instruction set. The frozen vectors in the
//! tests below pin the behavior; any intentional algorithm change must mint
//! new vectors explicitly, which makes replay drift reviewable.
//!
//! This is protocol/simulation randomness, never cryptographic randomness:
//! outputs are deterministic from the seed by design.

use kivi_core::RandomSource;

/// Deterministic 64-bit generator: SplitMix64-style, fully owned.
///
/// State transition per draw (all arithmetic modulo 2^64, which is inherent
/// to the mixing construction — not a counter semantic, so the project's
/// no-wrap rule for identities/sequences does not apply):
///
/// ```text
/// state += 0x9E3779B97F4A7C15
/// z = state
/// z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
/// z = (z ^ (z >> 27)) * 0x94D049BB133111EB
/// out = z ^ (z >> 31)
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimRng {
    state: u64,
}

impl SimRng {
    /// Creates a generator from an explicit seed. The same seed always
    /// yields the same stream, on every platform and every build.
    #[must_use]
    pub const fn seed_from_u64(seed: u64) -> Self {
        Self { state: seed }
    }

    /// Advances the state and returns one mixed draw.
    fn next_raw(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}

impl RandomSource for SimRng {
    fn next_u64(&mut self) -> u64 {
        self.next_raw()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Frozen vectors pin the algorithm bit-for-bit. They were generated by
    // this exact implementation (not copied from an external reference): any
    // future algorithm change must deliberately replace them.
    const SEED_42_STREAM: [u64; 4] = [
        0xBDD7_3226_2FEB_6E95,
        0x28EF_E333_B266_F103,
        0x4752_6757_130F_9F52,
        0x581C_E1FF_0E4A_E394,
    ];
    const SEED_0_FIRST_DRAW: u64 = 0xE220_A839_7B1D_CDAF;

    #[test]
    fn frozen_vectors_pin_the_algorithm() {
        let mut rng = SimRng::seed_from_u64(42);
        for expected in SEED_42_STREAM {
            assert_eq!(rng.next_u64(), expected);
        }
        assert_eq!(SimRng::seed_from_u64(0).next_u64(), SEED_0_FIRST_DRAW);
        // Replay from the same seed reproduces the frozen stream exactly.
        let mut replay = SimRng::seed_from_u64(42);
        for expected in SEED_42_STREAM {
            assert_eq!(replay.next_u64(), expected);
        }
    }

    #[test]
    fn same_seed_replays_identically() {
        let mut left = SimRng::seed_from_u64(42);
        let mut right = SimRng::seed_from_u64(42);
        for _ in 0..64 {
            assert_eq!(left.next_u64(), right.next_u64());
        }
    }

    #[test]
    fn different_seeds_diverge_immediately() {
        let mut left = SimRng::seed_from_u64(42);
        let mut right = SimRng::seed_from_u64(43);
        assert_ne!(left.next_u64(), right.next_u64());
    }

    #[test]
    fn helpers_stay_within_contract() {
        let mut rng = SimRng::seed_from_u64(7);
        for _ in 0..32 {
            assert_eq!(rng.below_u64(1), 0);
            assert!(rng.below_u64(1000) < 1000);
        }
        let mut left = SimRng::seed_from_u64(7);
        let mut right = SimRng::seed_from_u64(7);
        let mut a = [0u8; 20];
        let mut b = [0u8; 20];
        left.fill_bytes(&mut a);
        right.fill_bytes(&mut b);
        assert_eq!(a, b);
        assert_eq!(left.next_u32(), right.next_u32());
        assert_eq!(left.next_u128(), right.next_u128());
    }
}
