[package]
name = "kivi-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
kivi-types.workspace = true
kivi-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true
bytes.workspace = true
kivi-state.workspace = true
kivi-control.workspace = true
kivi-observation.workspace = true

[lints]
workspace = true
