[package]
name = "kivi-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
kivi-types.workspace = true
kivi-codec.workspace = true
hashbrown.workspace = true
bitflags.workspace = true
bytes.workspace = true
blake3.workspace = true
thiserror.workspace = true

[dev-dependencies]
divan.workspace = true
proptest.workspace = true

[lints]
workspace = true

[[bench]]
name = "semantic"
harness = false
