[package]
name = "kivi-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
kivi-types.workspace = true
kivi-state.workspace = true
kivi-tablet.workspace = true
kivi-protocol.workspace = true
bytes.workspace = true
arc-swap.workspace = true
crossbeam-channel.workspace = true
getrandom.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
