[package]
name = "kivi-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
kivi-types.workspace = true
blake3.workspace = true
crc32c.workspace = true
thiserror.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
